using FOMSApp.API.Data;
using FOMSApp.Shared.Models;
using Microsoft.EntityFrameworkCore;
using NetTopologySuite.IO.Converters; // Required for GeoJSON

var builder = WebApplication.CreateBuilder(args);

// ==========================================
// 1. CONFIGURATION
// ==========================================

// A. Database Connection & Spatial Support
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");
builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseSqlServer(connectionString, x => 
        x.UseNetTopologySuite())); 

// B. Enable CORS (Allows Client to talk to API)
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowAll", policy =>
    {
        policy.AllowAnyOrigin()
              .AllowAnyMethod()
              .AllowAnyHeader();
    });
});

// C. Register Controllers with GeoJSON Support
builder.Services.AddControllers()
    .AddJsonOptions(options => 
    {
        options.JsonSerializerOptions.Converters.Add(new GeoJsonConverterFactory());
    });

// D. Swagger / OpenAPI
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

// ==========================================
// 2. THE PIPELINE
// ==========================================

// A. Data Seeder (Runs on startup)
using (var scope = app.Services.CreateScope())
{
    var services = scope.ServiceProvider;
    try
    {
        var context = services.GetRequiredService<AppDbContext>();
        DbInitializer.Initialize(context); 
    }
    catch (Exception ex)
    {
        var logger = services.GetRequiredService<ILogger<Program>>();
        logger.LogError(ex, "An error occurred creating the DB.");
    }
}

// B. Middleware Setup
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

//app.UseHttpsRedirection(); // Disabled for simplicity in local dev

// IMPORTANT: CORS must be before Authorization
app.UseCors("AllowAll");

app.UseAuthorization();

app.MapControllers();

app.Run();

// Note: This file is the main entry point for the ASP.NET Core application. It sets up the web server, configures
// services, and defines a simple API endpoint for weather forecasting. This is boilerplate code generated by the .NET templates.