using FOMSApp.API.Data;
using Microsoft.EntityFrameworkCore; // For UseSqlServer and related EF Core methods

var builder = WebApplication.CreateBuilder(args); // Initializes the application builder

// Added Dependency Injection (DI) for our database connection ---
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection"); // Retrieves the connection string from appsettings.json

builder.Services.AddDbContext<AppDbContext>(options => // Configures the DbContext with SQL Server
    options.UseSqlServer(connectionString, x =>  // Configures SQL Server options to use Microsoft SQL Server
        x.UseNetTopologySuite())); // <--- This enables the Map/GIS features

// Add services to the container.
builder.Services.AddControllers();

// --- rest of the file below ---

// Add services to the container.
// Learn more about configuring OpenAPI at https://aka.ms/aspnet/openapi
builder.Services.AddOpenApi();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
}

app.UseHttpsRedirection();

var summaries = new[]
{
    "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
};

app.MapGet("/weatherforecast", () =>
{
    var forecast =  Enumerable.Range(1, 5).Select(index =>
        new WeatherForecast
        (
            DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
            Random.Shared.Next(-20, 55),
            summaries[Random.Shared.Next(summaries.Length)]
        ))
        .ToArray();
    return forecast;
})
.WithName("GetWeatherForecast");

app.Run();

record WeatherForecast(DateOnly Date, int TemperatureC, string? Summary)
{
    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
}

// Note: This file is the main entry point for the ASP.NET Core application. It sets up the web server, configures
// services, and defines a simple API endpoint for weather forecasting. This is boilerplate code generated by the .NET templates.