using FOMSApp.API.Data;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

// --- Enable CORS in the API ---
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowAll", policy =>
    {
        policy.AllowAnyOrigin()
              .AllowAnyMethod()
              .AllowAnyHeader();
    });
});
// ----------------------

// ==========================================
// 1. CONFIGURATION (The "Builder")
// ==========================================

// A. Get the connection string from appsettings.json
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");

// B. Register the Database Context
//    - Tells the app to use SQL Server
//    - ACTIVATES Spatial Data support (x.UseNetTopologySuite())
builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseSqlServer(connectionString, x => 
        x.UseNetTopologySuite())); 

// C. Register Standard API Services
builder.Services.AddControllers()
    .AddJsonOptions(options => 
    {
        // This converter translates the complex Map Point into standard JSON coordinates
        options.JsonSerializerOptions.Converters.Add(new NetTopologySuite.IO.Converters.GeoJsonConverterFactory());
    });
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

// ==========================================
// 2. THE PIPELINE (The "App")
// ==========================================

// A. Run the Data Seeder (The "Automatic Loader")
//    This runs ONCE every time the app starts to check for data.
using (var scope = app.Services.CreateScope())
{
    var services = scope.ServiceProvider;
    try
    {
        var context = services.GetRequiredService<AppDbContext>();
        // This calls the script we wrote in Step 6
        DbInitializer.Initialize(context); 
    }
    catch (Exception ex)
    {
        var logger = services.GetRequiredService<ILogger<Program>>();
        logger.LogError(ex, "An error occurred creating the DB.");
    }
}

// B. Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseCors("AllowAll"); // Enable CORS with the defined policy
app.UseAuthorization(); // Note: No authentication middleware is set up yet
app.MapControllers(); // Map controller routes

app.Run(); // Start the application

// Note: This file is the main entry point for the ASP.NET Core application. It sets up the web server, configures
// services, and defines a simple API endpoint for weather forecasting. This is boilerplate code generated by the .NET templates.